### ISSUE TITLE
Cloudformation links broken 

### ISSUE THREAD

**Issue by zachelliottwx** [aws-geospatial/amazon-location-samples-js#8]
On many samples the "launch stack" button results in an S3 error and inability to launch the stack. Going to the S3 link direct results in a forbidden message.

**Comment by curtisko-amzn** [comment]
@zachelliottwx , i just merged in the change, do you mind checking if it fixes it for you (i've verified it myself already but always good to get the issue reporter to check) :)

**Comment by zachelliottwx** [comment]
Looks good. Thank you.
